version: '3'

services:

  configserver:
    image: configserver:1.0
    container_name: configserver_container
    ports:
      - "8888:8888"
    depends_on:
      - eurekaserver
    restart: on-failure
    links:
      - eurekaserver

  eurekaserver:
    image: eurekaserver:1.0
    container_name: eurekaserver_container
    ports:
      - "8761:8761"


  users_db:
    image: mysql:5.7
    container_name: users_db_container
    restart: always
    environment:
      - MYSQL_DATABASE=artbook
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - users_db:/var/lib/mysql
    ports:
      - "3306:3306"
    depends_on:
      - eurekaserver

  userservice:
    image: userservice:1.0
    container_name: uservervice_container
    restart: always
    ports:
      - "8080:8080"
    links:
      - configserver
      - eurekaserver
      - users_db
    depends_on:
      - configserver
      - eurekaserver
      - users_db


volumes:
  users_db:


