version: '3'

services:
  eurekaserver:
    image:   eurekasvr:1.0
    ports:
      - "8761:8761"
  configserver:
    image: configserver:1.0
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_PORT: 8761
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"

  #  database:
  #  image: postgres:9.5
  #  ports:
  #   - "5432:5432"
  # environment:
  #   - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=p0stgr@s
  #     - POSTGRES_DB=eagle_eye_local

  user-service:
    image: userservice:1.0
    ports:
      - "8082:8082"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8082"
      ES_PORT:           9200
      DATABASE_PORT:     5432
      CONFIGSERVER_PORT: 8888
      EUREKASERVER_PORT: 8761
      AUTHSERVER_PORT:   8091
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"

