version: '3'

services:

  configserver:
    image: configserver:1.0
    ports:
      - "8888:8888"
    depends_on:
      - eurekaserver
    restart: on-failure
    links:
      - eurekaserver

  eurekaserver:
    image: eurekasvr:1.0
    ports:
      - "8761:8761"






volumes:
  users_db:


